(ns kotoba.lang.base-l2.abi-test
  "Known-answer tests for kotoba.lang.base-l2.abi, cross-checked against
  viem itself (this repo's own npm dependency) rather than hand-typed
  hex. `test/resources/base_l2/abi-vectors.json` was generated by a
  throwaway `node` script (using `import {encodeAbiParameters, ...} from
  \"viem\"`, run from this repo's root so it resolved viem from
  node_modules) that is NOT checked in -- only its JSON output is. To
  regenerate: write a script that calls viem's `encodeAbiParameters` /
  `decodeFunctionResult` / `toFunctionSelector` for the cases below and
  dump the results with `JSON.stringify`."
  (:require [clojure.test :refer [deftest is testing]]
            [clojure.string :as str]
            [clojure.data.json :as json]
            [clojure.java.io :as io]
            [kotoba.lang.base-l2.abi :as abi]
            [eth-crypto.core :as eth]))

(def ^:private vectors
  (json/read-str (slurp (io/resource "base_l2/abi-vectors.json")) :key-fn keyword))

(defn- hex= [a b] (= (str/lower-case a) (str/lower-case b)))

(deftest function-selector-test
  (testing "matches viem's toFunctionSelector for every signature this SDK calls"
    (is (= (get-in vectors [:selectors :anchor])
           (abi/function-selector "anchor(bytes32,bytes,uint64)")))
    (is (= (get-in vectors [:selectors :rootCount])
           (abi/function-selector "rootCount()")))
    (is (= (get-in vectors [:selectors :anchors])
           (abi/function-selector "anchors(bytes32)")))
    (is (= (get-in vectors [:selectors :join])
           (abi/function-selector "join(bytes32,string)")))
    (is (= (get-in vectors [:selectors :transfer])
           (abi/function-selector "transfer(address,uint256)")))))

(deftest encode-function-call-test
  (testing "anchor(bytes32,bytes,uint64) full calldata matches viem's encodeFunctionData"
    (let [root-hash (str "0x" (apply str (repeat 32 "11")))
          ipfs-cid (str "0x" (eth/bytes->hex (eth/utf8 "bafy-test-cid-123")))
          calldata (abi/encode-function-call "anchor(bytes32,bytes,uint64)"
                                              ["bytes32" "bytes" "uint64"]
                                              [root-hash ipfs-cid 42])]
      (is (hex= (get-in vectors [:encodeFunctionData :anchor]) calldata))))

  (testing "rootCount() has no args -- just the selector"
    (is (hex= (get-in vectors [:encodeFunctionData :rootCount])
              (abi/encode-function-call "rootCount()" [] []))))

  (testing "anchors(bytes32) calldata"
    (let [root-hash (str "0x" (apply str (repeat 32 "11")))]
      (is (hex= (get-in vectors [:encodeFunctionData :anchors])
                (abi/encode-function-call "anchors(bytes32)" ["bytes32"] [root-hash]))))))

(deftest decode-function-result-test
  (testing "rootCount() -> uint256"
    (let [data (get-in vectors [:decodeFunctionResult :rootCount :data])
          expected (bigint (get-in vectors [:decodeFunctionResult :rootCount :value]))
          [v] (abi/decode-function-result ["uint256"] data)]
      (is (= expected (bigint v)))))

  (testing "anchors(bytes32) return tuple: (bytes32, bytes, uint256, address, uint64, uint64)"
    (let [data (get-in vectors [:decodeFunctionResult :anchors :data])
          decoded (abi/decode-function-result ["bytes32" "bytes" "uint256" "address" "uint64" "uint64"] data)
          [root-hash ipfs-cid block-number anchorer batch-size anchored-at] decoded]
      (is (hex= (str "0x" (apply str (repeat 32 "22"))) root-hash))
      (is (hex= (str "0x" (eth/bytes->hex (eth/utf8 "bafy-anchor-cid"))) ipfs-cid))
      (is (= 999N (bigint block-number)))
      (is (hex= (get-in vectors [:decodeFunctionResult :anchors :anchorerAddr]) anchorer))
      (is (= 42N (bigint batch-size)))
      (is (= 1735689600N (bigint anchored-at))))))

(deftest encode-abi-params-general-test
  (let [ep (:encodeParams vectors)]
    (testing "uint256"
      (is (hex= (get-in ep [:uint256 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["uint256"] [123456789]))))))
    (testing "uint256 zero"
      (is (hex= (get-in ep [:uint256-zero :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["uint256"] [0]))))))
    (testing "uint8 max"
      (is (hex= (get-in ep [:uint8-max :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["uint8"] [255]))))))
    (testing "address is left-padded (value at the right)"
      (is (hex= (get-in ep [:address :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["address"] ["0x0000000000000000000000000000000000000abc"]))))))
    (testing "bool true/false"
      (is (hex= (get-in ep [:bool-true :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["bool"] [true])))))
      (is (hex= (get-in ep [:bool-false :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["bool"] [false]))))))
    (testing "bytes32 (already exactly 32 bytes)"
      (is (hex= (get-in ep [:bytes32 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["bytes32"] [(str "0x" (apply str (repeat 32 "ab")))]))))))
    (testing "bytes4 is RIGHT-padded (value at the left, unlike numbers)"
      (is (hex= (get-in ep [:bytes4 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["bytes4"] ["0xdeadbeef"]))))))
    (testing "bytes1"
      (is (hex= (get-in ep [:bytes1 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["bytes1"] ["0x7f"]))))))
    (testing "dynamic bytes (short, sub-word)"
      (is (hex= (get-in ep [:bytes-dynamic-short :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["bytes"] [(str "0x" (eth/bytes->hex (eth/utf8 "hi")))]))))))
    (testing "string (short)"
      (is (hex= (get-in ep [:string-short :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["string"] ["alice-on-github"]))))))
    (testing "string exactly 32 bytes (word boundary)"
      (is (hex= (get-in ep [:string-exact32 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["string"] ["12345678901234567890123456789012"]))))))
    (testing "string 33 bytes (crosses word boundary)"
      (is (hex= (get-in ep [:string-33 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["string"] ["123456789012345678901234567890123"]))))))
    (testing "empty string"
      (is (hex= (get-in ep [:string-empty :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["string"] [""]))))))
    (testing "(bytes32, string) -- the join()-shaped combo from paymaster.ts's own docstring example"
      (is (hex= (get-in ep [:bytes32-string :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["bytes32" "string"]
                                                                  [(str "0x" (apply str (repeat 32 "cd"))) "alice-on-github"]))))))
    (testing "(address, uint256) -- the transfer()-shaped combo"
      (is (hex= (get-in ep [:address-uint256 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["address" "uint256"]
                                                                  ["0x00000000000000000000000000000000000000ef" 1000000000000000000N]))))))
    (testing "uint64 small value still occupies a full 32-byte word"
      (is (hex= (get-in ep [:uint64-small :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["uint64"] [7]))))))
    (testing "int256 negative values (two's complement)"
      (is (hex= (get-in ep [:int256-neg1 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["int256"] [-1])))))
      (is (hex= (get-in ep [:int256-neg42 :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["int256"] [-42]))))))
    (testing "int8 min value"
      (is (hex= (get-in ep [:int8-min :data])
                (str "0x" (eth/bytes->hex (abi/encode-abi-params ["int8"] [-128]))))))))

(deftest decode-abi-params-roundtrip-test
  (testing "int256 negative values decode back correctly (roundtrip through the encode vectors)"
    (is (= -1N (bigint (first (abi/decode-abi-params ["int256"] (get-in vectors [:encodeParams :int256-neg1 :data]))))))
    (is (= -42N (bigint (first (abi/decode-abi-params ["int256"] (get-in vectors [:encodeParams :int256-neg42 :data]))))))
    (is (= -128N (bigint (first (abi/decode-abi-params ["int8"] (get-in vectors [:encodeParams :int8-min :data])))))))
  (testing "string roundtrip across a word boundary"
    (is (= "123456789012345678901234567890123"
           (first (abi/decode-abi-params ["string"] (get-in vectors [:encodeParams :string-33 :data]))))))
  (testing "bool roundtrip"
    (is (true? (first (abi/decode-abi-params ["bool"] (get-in vectors [:encodeParams :bool-true :data])))))
    (is (false? (first (abi/decode-abi-params ["bool"] (get-in vectors [:encodeParams :bool-false :data])))))))

(deftest unsupported-type-test
  (testing "arrays/tuples are explicitly out of scope"
    (is (thrown? clojure.lang.ExceptionInfo (abi/encode-abi-params ["uint256[]"] [[1 2 3]])))
    (is (thrown? clojure.lang.ExceptionInfo (abi/decode-abi-params ["(uint256,address)"] "0x00")))))
